TechCare_Prototipos/Controllers/ReservaController.cs
using Microsoft.AspNetCore.Mvc;
using Prototipos.BAL.Interfaces;
using Prototipos.DAL.ViewModels;

namespace TechCare_Prototipos.Controllers
{
    public class ReservaController : Controller
    {
        private readonly IReservasRepository reservasRepository;
        private readonly IMesasRepository mesasRepository;
        private readonly IMailNotificationService mailNotificationService;

        public ReservaController(IReservasRepository _reservasRepository, IMailNotificationService _mailNotificationService, IMesasRepository _mesasRepository)
        {
            reservasRepository = _reservasRepository;
            mailNotificationService = _mailNotificationService;
            mesasRepository = _mesasRepository;
        }

        public async Task<IActionResult> Index()
        {
            return View(new ReservaViewModel
            {
                MesasDisponibles = await mesasRepository.ListAsync()
            });
        }

        [HttpPost]
        public async Task<IActionResult> Reservar(ReservaViewModel model)
        {

            try
            {
                if (await reservasRepository.DoReserva(model))
                {
                    model.NotificationContent = new MailTemplates.ReservaCreationNotification()
                    {
                        Model = new ReservaNotificationViewModel
                        {
                            FechaReservada = model.FechaReserva,
                            MesaSeleccionada = model.MesaSeleccionada,
                            PersonaACargo = model.PersonaACargo
                        }
                    }.GenerateString();

                    await mailNotificationService.NotifyReserva(model);
                }

                return RedirectToAction("Success");
            }
            catch (Exception)
            {
                return RedirectToAction("Error");
            }
        }

        public IActionResult Success()
        {
            return View();
        }
    }
}

TechCare_Prototipos/Views/Reserva/Index.cshtml
@model ReservaViewModel

<div class="container">
    <div class="d-flex align-items-center flex-column">
        <div class="container col-lg-4 col-md-6">
            <form asp-action="Reservar" asp-controller="Reserva" method="post">
                <div class="text-center">
                    <h3>Reserva de Mesa</h3>
                </div>
                <div class="mb-3">
                    <label for="nombreApellido" class="form-label">Nombre y Apellido</label>
                    <input type="text" class="form-control" asp-for="PersonaACargo" required>
                </div>
                <div class="mb-3">
                    <label for="contacto" class="form-label">Contacto</label>
                    <input type="tel" class="form-control" asp-for="Contacto" required>
                </div>
                <div class="mb-3">
                    <label for="correo" class="form-label">Correo</label>
                    <input type="email" class="form-control" asp-for="Correo" required>
                </div>
                <div class="mb-3">
                    <label for="fechaReserva" class="form-label">Fecha de Reserva</label>
                    <input type="datetime-local" class="form-control" asp-for="FechaReserva" min="@Model.FechaReserva.AddHours(2).ToString("yyyy-MM-ddTHH:mm")" required>
                </div>
                <div class="mb-3">
                    <label for="mesa" class="form-label">Cantidad de personas</label>
                    <select class="form-select" asp-for="IdMesa" required>
                        <option value="" selected hidden>Seleccione cantidad de persona</option>

                        @foreach (var mesa in Model.MesasDisponibles)
                        {
                            <option value="@mesa.Id">@mesa.NombreMesa</option>
                        }

                    </select>
                </div>
                <div class="text-center">
                    <button type="submit" class="btn btn-primary mb-3">Reservar</button>
                </div>
            </form>
        </div>
    </div>
</div>

TechCare_Prototipos/Views/Reserva/Success.cshtml
<center class="mt-5">
    <h1>¡Reserva agendada correctamente!</h1>
    <h3>Revisa tu correo electronico para tener constancia de la reserva</h3>
    <a class="btn btn-outline-dark mt-3" asp-action="Index">Regresar</a>
</center>