TechCare_Prototipos/Controllers/AdministracionController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Prototipos.BAL.Helpers;
using Prototipos.BAL.Interfaces;
using Prototipos.DAL.Models;
using Prototipos.DAL.ViewModels;

namespace TechCare_Prototipos.Controllers
{
    [Authorize(Roles = $"{RolesReferences.ResourceOwner},{RolesReferences.Administrador}")]
    public class AdministracionController : Controller
    {
        private readonly IMesasRepository mesasRepository;
        private readonly IReservasRepository reservasRepository;
        private readonly IZonasRepository zonasRepository;

        public AdministracionController(IMesasRepository _mesasRepository, IZonasRepository _zonasRepository, IReservasRepository _reservasRepository)
        {
            mesasRepository = _mesasRepository;
            zonasRepository = _zonasRepository;
            reservasRepository = _reservasRepository;
        }

        public async Task<IActionResult> Index(MesasViewModel model)
        {
            if(model.IdEditarMesa > 0)
            {
                model.EditarMesa = await mesasRepository.GetByIdAsync(model.IdEditarMesa);
            }

            model.Mesas = await mesasRepository.ListAsync();
            model.Zonas = await zonasRepository.ListAsync();

            return View(model);
        }

        public IActionResult Productos()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> AgregarMesa(MesasViewModel model)
        {
            try
            {
                await mesasRepository.AddAsync(model.NuevaMesa);
                ViewBag.SuccessMessage = "Mesa agregada correctamente";
            }
            catch (Exception ex)
            {
                ViewBag.ErrorMessage = ex.Message;
            }

            return RedirectToAction("Index");
        }

        public async Task<IActionResult> Eliminar(int idMesa)
        {
            try
            {
                var mesa = await mesasRepository.GetByIdAsync(idMesa);

                await reservasRepository.DeleteReservasByMesaId(mesa.Id);

                if (mesa != null)
                    await mesasRepository.DeleteAsync(mesa);
                ViewBag.SuccessMessage = "Mesa eliminada correctamente";
            }
            catch (Exception ex)
            {
                ViewBag.ErrorMessage = ex.Message;
            }

            return RedirectToAction("Index");
        }

        public async Task<IActionResult> Editar(int idMesa)
        {   
            return RedirectToAction("Index", new MesasViewModel { IdEditarMesa = idMesa });
        }

        [HttpPost]
        public async Task<IActionResult> Editar(MesasViewModel model)
        {
            try
            {
                await mesasRepository.UpdateAsync(model.EditarMesa);
                ViewBag.SuccessMessage = "Mesa editada correctamente";
            }
            catch (Exception ex)
            {
                ViewBag.ErrorMessage = ex.Message;
            }

            return RedirectToAction("Index");
        }
    }
}

TechCare_Prototipos/Views/Administracion/Index.cshtml
@model MesasViewModel

@{
    ViewData["Title"] = "Crud de Mesas";

    var editar = Model.EditarMesa != null;
}

<div class="container my-4">
    <h1 class="text-center">Crud de Mesas</h1>

    <button id="agregarMesaButton" class="btn btn-success mb-3">Agregar Nueva Mesa</button>

    <table class="table table-bordered">
        <thead>
            <tr>
                <th>ID</th>
                <th>Mesa</th>
                <th>Cantidad de Personas</th>
                <th>Zona</th>
                <th>Acciones</th>
            </tr>
        </thead>
        <tbody>
            @foreach(var mesa in Model.Mesas)
            {
                <tr>
                    <td>@mesa.Id</td>
                    <td>@mesa.NombreMesa</td>
                    <td>@mesa.Personas</td>
                    <td>@mesa?.Zona?.NombreZona</td>
                    <td>
                        <a href="/Administracion/Editar?idMesa=@mesa.Id" class="btn btn-warning">Editar</a>
                        <a href="/Administracion/Eliminar?idMesa=@mesa.Id" class="btn btn-danger">Eliminar</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>

<div class="modal fade" id="agregarMesaModal" tabindex="-1" role="dialog" aria-labelledby="agregarMesaModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            @if (editar)
            {
                <form asp-action="Editar" asp-controller="Administracion" method="post">
                    @Html.HiddenFor(x=>x.EditarMesa.Id)
                    <div class="modal-header">
                        <h5 class="modal-title" id="agregarMesaModalLabel">Agregar Nueva Mesa</h5>
                        <button type="button" class="close" data-dismiss="modal" onclick="CerrarModal()" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">

                        <div class="form-group">
                            <label for="numeroMesa">Nombre de Mesa</label>
                            <input type="text" class="form-control" asp-for="EditarMesa.NombreMesa" required>
                        </div>
                        <div class="form-group">
                            <label for="cantidadPersonas">Cantidad de Personas</label>
                            <input type="number" class="form-control" asp-for="EditarMesa.Personas" required>
                        </div>
                        <div class="form-group">
                            <label for="zona">Zona</label>
                            <select class="form-select" asp-for="EditarMesa.IdZona" required>
                                <option value="" selected hidden>Seleccione una zona</option>
                                @foreach (var zona in Model.Zonas)
                                {
                                    <option value="@zona.Id">@zona.NombreZona</option>
                                }
                            </select>
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
                        <button id="submit" class="btn btn-primary">Editar</button>
                    </div>
                </form>
            }
            else
            {
                <form asp-action="AgregarMesa" asp-controller="Administracion" method="post">
                    <div class="modal-header">
                        <h5 class="modal-title" id="agregarMesaModalLabel">Agregar Nueva Mesa</h5>
                        <button type="button" class="close" data-dismiss="modal" onclick="CerrarModal()" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">

                        <div class="form-group">
                            <label for="numeroMesa">Nombre de Mesa</label>
                            <input type="text" class="form-control" asp-for="NuevaMesa.NombreMesa" required>
                        </div>
                        <div class="form-group">
                            <label for="cantidadPersonas">Cantidad de Personas</label>
                            <input type="number" class="form-control" asp-for="NuevaMesa.Personas" required>
                        </div>
                        <div class="form-group">
                            <label for="zona">Zona</label>
                            <select class="form-select" asp-for="NuevaMesa.IdZona" required>
                                <option value="" selected hidden>Seleccione una zona</option>

                                @foreach (var zona in Model.Zonas)
                                {
                                    <option value="@zona.Id">@zona.NombreZona</option>
                                }

                            </select>
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
                        <button id="submit" class="btn btn-primary">Guardar</button>
                    </div>
                </form>
            }
        </div>
    </div>
</div>

@section scripts{
    <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
    <script>
        // Mostrar el modal al hacer clic en "Agregar Nueva Mesa"
        $("#agregarMesaButton").click(function () {
            $("#numeroMesa").val("");
            $("#cantidadPersonas").val("");
            $("#zona").val("");
            MostrarModal();
        });

        $("#EliminarMesa").click(function () {
            swal("Mesa Eliminada", "La mesa ha sido eliminada exitosamente.", "success");
        });

        $("#EditarMesa").click(function () {
            $("#numeroMesa").val("3");
            $("#cantidadPersonas").val("3");
            $("#zona").val("Zona 3");
            MostrarModal();
        });

        // Mostrar la alerta de éxito al guardar
        $("#guardarMesaButton").click(function () {
            // Aquí debes agregar la lógica para guardar la nueva mesa (por ejemplo, una llamada a la API o AJAX)
            // Una vez guardada la mesa, muestra la alerta de éxito utilizando SweetAlert
            swal("Mesa Agregada", "La nueva mesa se ha agregado con éxito.", "success");

            // Cierra el modal
            CerrarModal();
        });

        function CerrarModal() {
            $("#agregarMesaModal").modal("hide");
        }

        function MostrarModal() {
            $("#agregarMesaModal").modal("show");
        }

    </script>

    @if (editar)
    {
        <text>
            <script type="text/javascript">
                $(document).ready(function () {
                    $("#agregarMesaModal").modal("show");
                });
            </script>
        </text>
    }

    @if (!string.IsNullOrEmpty(ViewBag.SuccessMessage))
    {
        <text>
            <script type="text/javascript">
                $(document).ready(function () {
                    Swal.fire({
                        icon: 'success',
                        title: 'Success',
                        text: '@Html.Raw(ViewBag.SuccessMessage)',
                    });
                });
            </script>
        </text>
    }

    @if (!string.IsNullOrEmpty(ViewBag.ErrorMessage))
    {
        <text>
            <script type="text/javascript">
                $(document).ready(function () {
                    Swal.fire({
                        icon: 'error',
                        title: 'Error',
                        text: '@Html.Raw(ViewBag.ErrorMessage)',
                    });
                });
            </script>
        </text>
    }

}

TechCare_Prototipos/Views/Administracion/Productos.cshtml
@{
    ViewData["Title"] = "Crud de Productos";
}

<div class="container my-4">
    <h1 class="text-center">Crud de Productos</h1>

    <button id="agregarProductoButton" class="btn btn-success mb-3">Agregar Nuevo Producto</button>

    <table class="table table-bordered">
        <thead>
            <tr>
                <th>ID</th>
                <th>Nombre</th>
                <th>Tipo de Producto</th>
                <th>Coste</th>
                <th>Precio Unitario</th>
                <th>Descripción</th>
                <th>Acciones</th>
            </tr>
        </thead>
        <tbody>
            <!-- Datos de ejemplo quemados -->
            <tr>
                <td>1</td>
                <td>Bebida 1</td>
                <td>Bebida</td>
                <td>2.5</td>
                <td>5.0</td>
                <td>Bebida refrescante</td>
                <td>
                    <button class="btn btn-primary VerImagen">Ver Imagen</button>
                    <button class="btn btn-warning EditarProducto">Editar</button>
                    <button id="EliminarProducto" class="btn btn-danger">Eliminar</button>
                </td>
            </tr>
            <tr>
                <td>2</td>
                <td>Postre 1</td>
                <td>Postre</td>
                <td>3.0</td>
                <td>7.0</td>
                <td>Postre delicioso</td>
                <td>
                    <button class="btn btn-primary VerImagen">Ver Imagen</button>
                    <button class="btn btn-warning EditarProducto">Editar</button>
                    <button id="EliminarProducto" class="btn btn-danger">Eliminar</button>
                </td>
            </tr>
        </tbody>
    </table>
</div>

<div class="modal fade" id="agregarProductoModal" tabindex="-1" role="dialog" aria-labelledby="agregarProductoModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="agregarProductoModalLabel">Agregar Nuevo Producto</h5>
                <button type="button" class="close" data-dismiss="modal" onclick="VerifyCloseModal()" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <form id="nuevoProductoForm">
                    <div class="form-group">
                        <label for="nombre">Nombre</label>
                        <input type="text" class="form-control" id="nombre" name="nombre" required>
                    </div>
                    <div class="form-group">
                        <label for="tipoProducto">Tipo de Producto</label>
                        <select class="form-control" id="tipoProducto" name="tipoProducto" required>
                            <option value="Bebida">Bebida</option>
                            <option value="Postre">Postre</option>
                            <option value="Almuerzo">Almuerzo</option>
                            <option value="Cena">Cena</option>
                        </select>
                    </div>
                    <div class="form-group">
                        <label for="coste">Coste</label>
                        <input type="number" class="form-control" id="coste" name="coste" required>
                    </div>
                    <div class="form-group">
                        <label for="precioUnitario">Precio Unitario</label>
                        <input type="number" class="form-control" id="precioUnitario" name="precioUnitario" required>
                    </div>
                    <div class="form-group">
                        <label for="descripcion">Descripción</label>
                        <textarea class="form-control" id="descripcion" name="descripcion" rows="3" required></textarea>
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button id="cancelarProductoButton" type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
                <button id="guardarProductoButton" class="btn btn-primary">Guardar</button>
            </div>
        </div>
    </div>
</div>


@section scripts{
    <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
    <script>
        // Mostrar el modal al hacer clic en "Agregar Nuevo Producto"
        $("#agregarProductoButton").click(function () {
            $("#agregarProductoModal").modal("show");
        });

        // Mostrar la alerta de éxito al guardar
        $("#guardarProductoButton").click(function () {
            // Aquí debes agregar la lógica para guardar el nuevo producto (por ejemplo, una llamada a la API o AJAX)
            // Una vez guardado el producto, muestra la alerta de éxito utilizando SweetAlert
            swal("Producto Agregado", "El nuevo producto se ha agregado con éxito.", "success");

            // Cierra el modal
            $("#agregarProductoModal").modal("hide");
        });

        $(".VerImagen").click(function () {

            var imageUrl = "https://c.files.bbci.co.uk/DBBF/production/_105055265_bandejapaisa.jpg";

            var imgElement = document.createElement("img");
            imgElement.src = imageUrl;
            imgElement.style.width = "100%";

            swal({
                content: imgElement
            });
        });

        $("#EliminarProducto").click(function () {
            swal("Producto Eliminada", "El producto ha sido eliminado exitosamente.", "success");
        });

        $(".EditarProducto").click(function () {
            $("#nombre").val("Producto 1");
            $("#tipoProducto").val("Almuerzo");
            $("#coste").val("10.50");
            $("#precioUnitario").val("15.75");
            $("#descripcion").val("Almuerzo");
            $("#agregarProductoModal").modal("show");
        });

        $("#cancelarProductoButton").click(function () {
            VerifyCloseModal();
        });

        function VerifyCloseModal() {
            // Verificar si al menos uno de los campos está lleno
            var nombre = $("#nombre").val();
            var tipoProducto = $("#tipoProducto").val();
            var coste = $("#coste").val();
            var precioUnitario = $("#precioUnitario").val();
            var descripcion = $("#descripcion").val();

            if (nombre != "" || coste != "" || precioUnitario != "" || descripcion != "") {
                // Mostrar modal de confirmación con SweetAlert
                swal({
                    title: "Cancelar Producto",
                    text: "¿Desea cancelar y perder la información?",
                    icon: "warning",
                    buttons: ["No", "Sí"],
                    dangerMode: true,
                })
                    .then((willCancel) => {
                        if (willCancel) {
                            // Usuario eligió cancelar, cierra el modal
                            $("#agregarProductoModal").modal("hide");
                            $("#nombre").val("");
                            $("#tipoProducto").val("");
                            $("#coste").val("");
                            $("#precioUnitario").val("");
                            $("#descripcion").val("");
                        }
                    });
            } else {
                // Si ningún campo está lleno, simplemente cierra el modal
                $("#agregarProductoModal").modal("hide");
            }
        }
    </script>
}