TechCare_Prototipos/Controllers/AuthController.cs
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Mvc;
using Prototipos.BAL.Helpers;
using Prototipos.BAL.Interfaces;
using Prototipos.DAL.ViewModels;
using System.Security.Claims;

namespace TechCare_Prototipos.Controllers
{
    public class AuthController : Controller
    {
        private readonly IAuthService authService;
        private readonly IUsuariosRepository usuariosRepository;
        private readonly IZonasRepository zonasRepository;
        private readonly IMesasRepository mesasRepository;

        public AuthController(IAuthService _authService, IUsuariosRepository _usuariosRepository, IZonasRepository _zonasRepository, IMesasRepository _mesasRepository)
        {
            authService = _authService;
            usuariosRepository = _usuariosRepository;
            zonasRepository = _zonasRepository;
            mesasRepository = _mesasRepository;
        }

        public async Task<IActionResult> Index()
        {
            await Seed.SeedUsers(usuariosRepository);
            await Seed.SeedZonas(zonasRepository);
            await Seed.SeedMesas(mesasRepository);
            return RedirectToAction("Login");
        }

        public async Task<IActionResult> Login()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Login(LoginViewModel model)
        {            
            if(authService.TryLogin(model, out ClaimsPrincipal claimsPrincipal))
            {
                await HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, claimsPrincipal);

                var role = claimsPrincipal.FindFirst(ClaimTypes.Role)?.Value ?? "default";

                return RedirectToAction(ViewsByRole.Dictionary[role].Action, ViewsByRole.Dictionary[role].Controller);
            }

            return View();
        }

        public async Task<IActionResult> Logout()
        {
            await HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);
            return View();
        }
        public IActionResult Denied() => View();
    }
}

TechCare_Prototipos/Controllers/CajaController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Prototipos.BAL.Helpers;

namespace TechCare_Prototipos.Controllers
{
    [Authorize(Roles = $"{RolesReferences.Cajero},{RolesReferences.Gerente},{RolesReferences.ResourceOwner}")]
    public class CajaController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Finalizar()
        {
            return View();
        }

        public IActionResult Detalle()
        {
            return View();
        }

        public IActionResult Ticket()
        {
            return View();
        }
    }
}

TechCare_Prototipos/Controllers/CocinaController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Prototipos.BAL.Helpers;

namespace TechCare_Prototipos.Controllers
{
    [Authorize(Roles = $"{RolesReferences.Cocinero},{RolesReferences.Gerente},{RolesReferences.ResourceOwner}")]
    public class CocinaController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

TechCare_Prototipos/Controllers/ComedorController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Prototipos.BAL.Helpers;
using Prototipos.BAL.Interfaces;
using Prototipos.DAL.Models;
using Prototipos.DAL.ViewModels;

namespace TechCare_Prototipos.Controllers
{
    [Authorize(Roles = $"{RolesReferences.Mesero},{RolesReferences.Gerente},{RolesReferences.ResourceOwner}")]
    public class ComedorController : Controller
    {
        private readonly IMesasRepository mesasRepository;
        private readonly ICuentasRepository cuentasRepository;
        private readonly IUsuariosRepository usuariosRepository;

        public ComedorController(IMesasRepository _mesasRepository, ICuentasRepository _cuentasRepository, IUsuariosRepository _usuariosRepository)
        {
            mesasRepository = _mesasRepository;
            cuentasRepository = _cuentasRepository;
            usuariosRepository = _usuariosRepository;
        }

        public async Task<IActionResult> Index()
        {
            return View(await mesasRepository.GetComedor());
        }

        public IActionResult Detalle(bool? Success)
        {
            if (Success.HasValue && Success.Value)
            {
                ViewBag.Success = true;
            }

            return View();
        }

        public IActionResult NuevaOrden()
        {
            return View();
        }

        public async Task<IActionResult> Asignar(int idMesa)
        {
            var userId = User.FindFirst(System.Security.Claims.ClaimTypes.NameIdentifier)?.Value;

            return View(new CrearCuentaViewModel
            {
                Mesa = await mesasRepository.GetByIdAsync(idMesa),
                Reserva = await mesasRepository.GetReservaInfo(idMesa),
                Mesero = await usuariosRepository.GetByIdAsync(int.Parse(userId))
            });
        }

        [HttpPost]
        public async Task<IActionResult> Asignar(CrearCuentaViewModel cuenta)
        {
            try
            {
                await cuentasRepository.CreateCuentaByViewModel(cuenta);
                return RedirectToAction("Index");
            }
            catch (Exception)
            {
                return View();
            }
        }
    }
}

TechCare_Prototipos/Views/Shared/_HomeModuleByRole.cshtml
@if (User != null && (User.IsInRole(RolesReferences.Cocinero) || User.IsInRole(RolesReferences.ResourceOwner)))
{
    <a class="navbar-brand" asp-area="" asp-controller="Cocina" asp-action="Index">TechCare</a>
}
else if (User != null && (User.IsInRole(RolesReferences.Mesero) || User.IsInRole(RolesReferences.ResourceOwner)))
{
    <a class="navbar-brand" asp-area="" asp-controller="Comedor" asp-action="Index">TechCare</a>
}
else if (User != null && (User.IsInRole(RolesReferences.Cajero) || User.IsInRole(RolesReferences.ResourceOwner)))
{
    <a class="navbar-brand" asp-area="" asp-controller="Caja" asp-action="Index">TechCare</a>
}
else if (User != null && (User.IsInRole(RolesReferences.Administrador) || User.IsInRole(RolesReferences.ResourceOwner)))
{
    <a class="navbar-brand" asp-area="" asp-controller="Administracion" asp-action="Index">TechCare</a>
}
else if (User != null && (User.IsInRole(RolesReferences.Gerente) || User.IsInRole(RolesReferences.ResourceOwner)))
{
    <a class="navbar-brand" asp-area="" asp-controller="Reporte" asp-action="Index">TechCare</a>
}
else
{
    <a class="navbar-brand" asp-area="" asp-controller="Reserva" asp-action="Index">TechCare</a>
}

TechCare_Prototipos/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TechCare</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/TechCare_Prototipos.styles.css" asp-append-version="true" />
    <link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/toastify-js/src/toastify.min.css">
    @await RenderSectionAsync("Styles", required: false)
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                @Html.Partial("_HomeModuleByRole")
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        @Html.Partial("_ModulesByRole")
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script type="text/javascript" src="https://cdn.jsdelivr.net/npm/toastify-js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

TechCare_Prototipos/Views/Shared/_ModulesByRole.cshtml
@if (User == null || User.Identity == null || !User.Identity.IsAuthenticated)
{
    <li class="nav-item">
        <a class="nav-link text-dark" asp-area="" asp-controller="Auth" asp-action="Login">Login</a>
    </li>
}

@if (User != null && (User.IsInRole(RolesReferences.Mesero) || User.IsInRole(RolesReferences.Gerente) || User.IsInRole(RolesReferences.ResourceOwner)))
{
    <li class="nav-item">
        <a class="nav-link text-dark" asp-area="" asp-controller="Comedor" asp-action="Index">Comedor</a>
    </li>
}
@if (User != null && (User.IsInRole(RolesReferences.Cajero) || User.IsInRole(RolesReferences.Gerente) || User.IsInRole(RolesReferences.ResourceOwner)))
{
    <li class="nav-item">
        <a class="nav-link text-dark" asp-area="" asp-controller="Caja" asp-action="Index">Caja</a>
    </li>
}
@if (User != null && (User.IsInRole(RolesReferences.Cocinero) || User.IsInRole(RolesReferences.Gerente) || User.IsInRole(RolesReferences.ResourceOwner)))
{
    <li class="nav-item">
        <a class="nav-link text-dark" asp-area="" asp-controller="Cocina" asp-action="Index">Cocina</a>
    </li>
}
@if (User != null && (User.IsInRole(RolesReferences.Gerente) || User.IsInRole(RolesReferences.ResourceOwner)))
{
    <li class="nav-item">
        <a class="nav-link text-dark" asp-area="" asp-controller="Reporte" asp-action="Index">Reporte</a>
    </li>
}
@if (User != null && (User.IsInRole(RolesReferences.Administrador) || User.IsInRole(RolesReferences.ResourceOwner)))
{
    <li class="nav-item dropdown">
        <a class="nav-link text-dark dropdown-toggle" href="#" id="adminDropdown" role="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Administración
        </a>
        <div class="dropdown-menu" aria-labelledby="adminDropdown">
            <a class="dropdown-item" asp-controller="Administracion" asp-action="Index">Mesas</a>
            <a class="dropdown-item" asp-controller="Administracion" asp-action="Productos">Productos</a>
        </div>
    </li>
}

@if (User != null && User.Identity != null && User.Identity.IsAuthenticated)
{
    <li class="nav-item">
        <a class="nav-link text-dark" asp-area="" asp-controller="Auth" asp-action="Logout">Logout</a>
    </li>
}  

TechCare_Prototipos/Views/Shared/_NoAuthLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TechCare_Prototipos</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/TechCare_Prototipos.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                @Html.Partial("_HomeModuleByRole")
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                       @* <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Auth" asp-action="Login">Login</a>
                        </li>*@
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - TechCare_Prototipos - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>